/* Database schema to keep the structure of entire database. */

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

-- Table: public.animals

-- DROP TABLE IF EXISTS public.animals;

CREATE TABLE IF NOT EXISTS public.animals
(
    id INT GENERATED ALWAYS AS IDENTITY,
    name character(150) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    escape_attempts smallint NOT NULL DEFAULT 0,
    neutered boolean NOT NULL DEFAULT 'false',
    weight_kg numeric(10,2)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.animals
    OWNER to postgres;

/* Add a column species of type string to your animals table. Modify your schema.sql file. */
BEGIN;
ALTER TABLE animals
ADD COLUMN species VARCHAR(200);
COMMIT;


/* Create a table named owners with the following column */

BEGIN;
CREATE TABLE owners(
  id INT GENERATED ALWAYS AS IDENTITY,
  full_name VARCHAR(200),
  age INT,
  PRIMARY KEY(id)
);
COMMIT;
