/* Database schema to keep the structure of entire database. */

-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

CREATE DATABASE IF NOT EXISTS vet_clinic
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'Spanish_Spain.1252'
    LC_CTYPE = 'Spanish_Spain.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

CREATE TABLE IF NOT EXISTS public.animals
(
    id integer NOT NULL,
    name character(150) NOT NULL,
    date_of_birth date,
    escape_attempts smallint NOT NULL DEFAULT 0,
    neutered boolean NOT NULL DEFAULT 'false',
    weight_kg numeric(10, 2)
);
END;