-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.animals
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character(150) COLLATE pg_catalog."default" NOT NULL,
    date_of_birth date,
    escape_attempts smallint NOT NULL DEFAULT 0,
    neutered boolean NOT NULL DEFAULT 'false',
    weight_kg numeric(10, 2),
    species_id integer,
    owner_id integer,
    CONSTRAINT animals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.owners
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    full_name character varying(200) COLLATE pg_catalog."default",
    age integer,
    CONSTRAINT owners_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.specializations
(
    vet_id integer NOT NULL,
    species_id integer NOT NULL,
    CONSTRAINT specializations_pkey PRIMARY KEY (vet_id, species_id)
);

CREATE TABLE IF NOT EXISTS public.species
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default",
    CONSTRAINT species_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vets
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default",
    age integer,
    date_of_graduation date,
    CONSTRAINT vets_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.visits
(
    animal_id integer NOT NULL,
    vet_id integer NOT NULL,
    date_of_visits date NOT NULL,
    CONSTRAINT visits_pkey PRIMARY KEY (animal_id, vet_id, date_of_visits)
);

ALTER TABLE IF EXISTS public.animals
    ADD CONSTRAINT dk_owner_id FOREIGN KEY (owner_id)
    REFERENCES public.owners (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.animals
    ADD CONSTRAINT fk_species_id FOREIGN KEY (species_id)
    REFERENCES public.species (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.specializations
    ADD CONSTRAINT specializations_species_id_fkey FOREIGN KEY (species_id)
    REFERENCES public.species (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.specializations
    ADD CONSTRAINT specializations_vet_id_fkey FOREIGN KEY (vet_id)
    REFERENCES public.vets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.visits
    ADD CONSTRAINT visits_animal_id_fkey FOREIGN KEY (animal_id)
    REFERENCES public.animals (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.visits
    ADD CONSTRAINT visits_vet_id_fkey FOREIGN KEY (vet_id)
    REFERENCES public.vets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;